# Generated by Django 4.2.1 on 2024-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
