# Generated by Django 4.2.1 on 2024-02-17 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brandprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='brand_description',
            field=models.CharField(default='Default description', max_length=500, validators=[django.core.validators.MinLengthValidator(150)]),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='brand_name',
            field=models.CharField(default='Brand Name', max_length=255),
        ),
    ]
